name: Deploy FastAPI to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          printf "%s\n" "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/aws_key.pem
          chmod 600 ~/.ssh/aws_key.pem
          echo "🔒 First line of key file:"
          head -n 1 ~/.ssh/aws_key.pem
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/aws_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd aws-learning
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            sudo fuser -k 80/tcp || true
            sudo nohup uvicorn main:app --host 0.0.0.0 --port 80 > fastapi.log 2>&1 &
          EOF
